---
- hosts: stevenberg.net
  become: yes
  roles:
    - common
    - major.mailgun

- hosts: web
  become: yes
  roles:
    - web

- hosts: ruby
  become: yes
  roles:
    - ruby

- hosts: php
  become: yes
  roles:
    - php

- hosts: mariadb
  become: yes
  roles:
    - mariadb

- hosts: mariadb-client
  become: yes
  roles:
    - mariadb-client

- hosts: postgresql
  become: yes
  roles:
    - postgresql

- hosts: postgresql-client
  become: yes
  roles:
    - postgresql-client
