---
- name: restart ssh
  service: name=ssh state=restarted
- name: reload services
  command: systemctl daemon-reload
- name: restart spiped services
  service: name=spiped-{{ item.name }} state=restarted
  with_items: "{{ common_spiped_services + spiped_services }}"
